---
worker_count: 3
tasks:
  - type: sleep
    config:
      duration: 2s

  - type: sleep
    config:
      duration: 10s

  - type: sleep
    config:
      duration: 5s

  - type: sleep
    config:
      duration: 4s

  - type: copy_file
    config:
#      source: /home/vsokolov/tmp/1/file.data
#      destination: /home/vsokolov/tmp/2/file2.data
      source: /Users/vsokolov/tmp/1/file.data
      destination: /Users/vsokolov/tmp/2/file2.data